#!/bin/bash
# Update all yum package repositories
yum update -y
# Install Apache Web Server
yum install -y httpd.x86_64
# Start and Enable Apache Web Server
systemctl start httpd.service
systemctl enable httpd.service
# Add our custom webpage HTML code to "index.html" file.
sudo echo "<h1>Welcome to My Website</h1>" > /var/www/html/index.html
